# Generated by Django 4.2.3 on 2023-08-04 11:49

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("flight_id", models.CharField(max_length=100)),
                ("callsign", models.CharField(max_length=20)),
                ("origin", models.CharField(max_length=100)),
                ("user_email", models.CharField(default=None, max_length=50)),
                ("destination", models.CharField(max_length=100)),
                ("aircraft_type", models.CharField(max_length=50)),
                ("aircraft_tail", models.CharField(max_length=10)),
                ("distance", models.IntegerField()),
                (
                    "flight_time",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                ("flight_date", models.CharField(max_length=100)),
                ("time_stamp", models.DateTimeField()),
                ("live", models.BooleanField()),
                ("track", models.BooleanField()),
                (
                    "origin_coordinates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        default=main.models.default_coordinates,
                        size=None,
                    ),
                ),
                (
                    "destination_coordinates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        default=main.models.default_coordinates,
                        size=None,
                    ),
                ),
            ],
            options={"db_table": "flights",},
        ),
    ]
