# Generated by Django 4.2.3 on 2023-08-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("flight_id", models.CharField(max_length=100)),
                ("callsign", models.CharField(max_length=20)),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("aircraft_type", models.CharField(max_length=50)),
                ("aircraft_tail", models.CharField(max_length=10)),
                ("distance", models.IntegerField()),
                ("flight_time", models.IntegerField()),
                ("flight_date", models.DateField()),
                ("live", models.BooleanField()),
                ("track", models.BooleanField()),
            ],
            options={"db_table": "flights",},
        ),
    ]
