# Generated by Django 4.2.3 on 2023-08-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="flight_date",
            field=models.CharField(max_length=100),
        ),
    ]
