# Generated by Django 4.2.3 on 2023-08-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_flight_flight_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="user_email",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
