# Generated by Django 4.2.3 on 2023-08-02 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_flight_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="time_stamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
