# Generated by Django 4.2.3 on 2023-08-03 16:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_flight_time_stamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="destination_coordinates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), default=[0.0, 0.0], size=None
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="origin_coordinates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), default=[0.0, 0.0], size=None
            ),
        ),
    ]
