# Generated by Django 4.2.3 on 2023-08-03 16:54

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_flight_destination_coordinates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="destination_coordinates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=main.models.default_coordinates,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="origin_coordinates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=main.models.default_coordinates,
                size=None,
            ),
        ),
    ]
